version: '3.8'
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/javascript-node:20
    volumes:
      - ../..:/workspaces:cached
      - cms-bash-history:/commandhistory
    command: sleep infinity

volumes:
  cms-bash-history:
