#!/bin/bash

echo "Check branch name..."
node .husky/check-branch-name.js $(git rev-parse --abbrev-ref HEAD)

echo "Check commit message..."
npx --no -- commitlint --edit $1

echo "Check style..."
nx format:check

echo "Lint source code..."
nx run-many --target lint
